### ISSUE TITLE
Negative register values in F6.7.json and F7.7.json

### ISSUE THREAD

**Issue by matushorvath** [SingleStepTests/8088#1]
Some `final.regs.ip` values in F6.7.json and F7.7.json are negative:

```sh
bash-5.2$ grep '"ip": -' *.json
F6.7.json:            "ip": -988355
F6.7.json:            "ip": -1008415
F6.7.json:            "ip": -1019276
F6.7.json:            "ip": -1004376
F6.7.json:            "ip": -993597
F6.7.json:            "ip": -989439
F6.7.json:            "ip": -1011427
F6.7.json:            "ip": -1018735
F7.7.json:            "ip": -987801
F7.7.json:            "ip": -1024038
F7.7.json:            "ip": -1023823
F7.7.json:            "ip": -983466
F7.7.json:            "ip": -1003823
F7.7.json:            "ip": -986500
F7.7.json:            "ip": -1010142
```

To get the correct final values of IP for these tests, I had to increase them by 0x100000.
```js
    for (const test of tests) {
        if (test.final.regs.ip < 0) {
            test.final.regs.ip += 0x100000;
        }
    }
```

Expected: Since IP is a 16-bit register, all final.regs.ip values should be in the range 0x0000-0xffff. Signed 16-bit values would also be acceptable, although not ideal.

Actual: These values are not valid 16-bit numbers, either signed or unsigned. They are valid as signed 20-bit numbers, but that is a strange way to represent a 16-bit register.

**Comment by matushorvath** [comment]
PS: Please let me know if this is the correct channel to report findings in these tests.

Also, thank you for providing this data for free. I am working on an 8086 VM (for hobby purposes) and your test data is a small miracle to have. I have already found so many bugs in my code :).

**Comment by dbalsom** [comment]
Thanks for the report. I think I pieced together what happened.

Storytime: the original test set for DIV had bad IP values when exceptions occurred due to a bug in my Arduino code.  I probably should have fixed the code and re-generated the tests, but they took a long time to run so I thought it would be faster to fix the ending IP of the offending tests with a python script.

The actual ending CS:IP is easy enough to extract from the cycle states, it is the address of the first code fetch after the IVT of the exception handler is read.  But that's the full 20-bit address, not the 16-bit portion of which that represents IP.  So I had to subtract the segment value << 4 from the address. 

I am used to working in Rust with well-established integer wrapping mechanics, so I didn't consider that some of the adjustments done in this script would be negative. I also didn't catch it when I ran the tests myself since Rust serializes that field back into a u16 which automatically 'corrected' the value for me. I think you will find that ANDing the value with 0xFFFF has the same effect as adding 0x100000.

**Comment by dbalsom** [comment]
> PS: Please let me know if this is the correct channel to report findings in these tests.

Absolutely correct channel, thank you.

> Also, thank you for providing this data for free. I am working on an 8086 VM (for hobby purposes) and your test data is a small miracle to have. I have already found so many bugs in my code :).

You're welcome! This test set is my gift to the emulation community and I'm very pleased it has helped several people already.

I don't know if you are planning on cycle-accuracy, but I recently figured out how to set up an instruction in a fully-prefetched state. I am planning on re-generating the test set with 50% fully prefetched instructions which will provide a lot more visibility of true instruction timings. The board is now fast enough to use a non-CMOS CPU (despite being a clone, I expect there are tiny differences in the Harris 80c88 from the original 8088), so I was planning on switching CPUs as well.

All the bugs with exception handling and IP have been worked out. No more fixing stuff after the fact with Python, I promise. :D

**Comment by matushorvath** [comment]
> Storytime: the original test set for DIV had bad IP values when exceptions occurred due to a bug in my Arduino code. I probably should have fixed the code and re-generated the tests, but they took a long time to run so I thought it would be faster to fix the ending IP of the offending tests with a python script.

Oh, in that case, is it possible that the IP pushed on stack is still wrong by 2 in your data, when #DE happens inside a DIV/IDIV?

I first tested my VM against bochs, just writing some test cases by hand, booting that code using both bochs and my VM, and comparing the CPU state. When #DE happens inside a DIV/IDIV, bochs pushes CS:IP of the DIV/IDIV instruction on stack, which I think is consistent with the documentation. But in your test data the stack contains CS:IP *after* the DIV/IDIV. I decided bochs is probably wrong, but if you're saying you modified IP in exactly that case using a script...

For example, 25daeaea3b6b238081aa8235a77cee77bb9cd065 in F6.6:

initial RAM:
```json
        "ram": [
            [0, 0],
            [1, 4],
            [2, 0],
            [3, 0],
            [1024, 144],
            [59678, 246],
            [59679, 53],
            [59680, 144],
            [59681, 144],
            [59682, 144],
            [59683, 144],
            [658804, 28]
        ],
```

final RAM:
```json
        "ram": [
            [405927, 16],   // IP lo
            [405928, 193],  // IP hi
            [405929, 129],  // CS lo
            [405930, 2],    // CS hi
            [405931, 6],    // flags lo
            [405932, 240]   // flags hi
        ],
```

The address of the DIV instruction where #DE happens is 59678

The stack in the test data contains:
  CS = 2 * 256 + 129 = 641
  IP = 193 * 256 + 16 = 49424
  => physical address = CS * 16 + IP = 641 * 16 + 49424 = 59680, address of the instruction after the DIV

Looking at https://cdrdv2.intel.com/v1/dl/getContent/671447, page 6-34:
> Saved contents of CS and EIP registers point to the instruction that generated the exception.

Is it possible this is still something that needs to be changed in your data, or am I making a mistake somewhere?

Thank you!

**Comment by dbalsom** [comment]
> Oh, in that case, is it possible that the IP pushed on stack is still wrong by 2 in your data, when #DE happens inside a DIV/IDIV?

No, because that would have occurred during the instruction execution itself and should be accurate. The reason IP was off at the end is because the register store program runs after the instruction in question has finished and has to calculate the value of IP as it is at that precise point. It does this by doing a dummy CALL and intercepting the IP written to the stack, and then rewinding it by some appropriate offset. The offset was just not correct when the STORE program was running in the exception handler.

> I first tested my VM against bochs, just writing some test cases by hand, booting that code using both bochs and my VM, and comparing the CPU state. When #DE happens inside a DIV/IDIV, bochs pushes CS:IP of the DIV/IDIV instruction on stack, which I think is consistent with the documentation. But in your test data the stack contains CS:IP _after_ the DIV/IDIV. I decided bochs is probably wrong, but if you're saying you modified IP in exactly that case using a script...

> Is it possible this is still something that needs to be changed in your data, or am I making a mistake somewhere?

You're not making a mistake, we just have to differentiate certain behavior between the 8088 and later Intel CPUs.  Bochs does not emulate an 8088, it emulates the generic Intel IA-32 ISA. 

One of the key things is that the 8088 doesn't really have "exceptions". Sure we call it a division exception, but Intel refers to it in the original 8088 manuals as a "Type-0 interrupt", and it behaves like any other interrupt would, pushing the return value of the next instruction.

![image](https://github.com/SingleStepTests/8088/assets/7229541/0730cdbe-41a5-40c9-9cb2-cdf3b8eced0d)

So with the 286 we got proper exceptions, and now DIV generates a #DE instead of a Type-0 interrupt, and this changes the return address behavior. 

This had a rare affect on software compatibility. Microsoft Flight Simulator 1.0 divides by 0 quite often.  It will only run on a proper 8088, because it's allowed to continue from that point after the exception handler runs.  On later chips, the exception handler - despite not programmed to be able to fix the situation - returns to the DIV, which divides by 0 again, throws another exception, and so and we get stuck in an infinite loop.

If we read generic Intel documentation they pretty much only discuss how things are from a post-8088 perspective. When dealing with the 8088's quirks we often have to go back and consult the Old Tomes.

I will add a note about the DIV exception behavior in the README.

**Comment by matushorvath** [comment]
Thank you, that makes sense. I do have the 8086/8088 documentation as a PDF and mostly use that, and they don't mention anything about different behavior of different interrupts, which confirms what you say.

**Comment by dbalsom** [comment]
Corrected the negative values. Thanks again for the report. 
https://github.com/SingleStepTests/8088/commit/2e43aacadd1f523e93b5f3310d34c1055c97226c
